In [1]:
from __future__ import print_function
import torch

# Constructing an empty matrix of dimension 5*3
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -4.6566e-10,  0.0000e+00],
        [-4.6566e-10,  7.0065e-45,  1.1614e-41],
        [ 0.0000e+00,  2.2369e+08,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [        nan,         nan,  7.8021e+09]])


In [2]:
# Construct a randomly initialised matrix of dimension 5*3
x = torch.rand(5,3)
print(x)

tensor([[ 0.5157,  0.6584,  0.6884],
        [ 0.7624,  0.2386,  0.7284],
        [ 0.8996,  0.3620,  0.9657],
        [ 0.1371,  0.9561,  0.6004],
        [ 0.6710,  0.0285,  0.8256]])


In [3]:
# Construct a matrix filled zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [5]:
# Construct a tensor directly from data
y = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [9]:
z= torch.rand(5, 3)
x = torch.rand(5, 3)
print(torch.add(x, z))

tensor([[ 0.8605,  0.5812,  0.7268],
        [ 0.5211,  1.2150,  1.0916],
        [ 0.5947,  0.5399,  1.7641],
        [ 1.2825,  0.9270,  0.4586],
        [ 1.0095,  1.2099,  0.8628]])


In [10]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]


In [12]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]
